version: '3.8'

services:
  ecoshakti:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_SECRET_KEY=your_production_secret_key_here
      - DATABASE_URL=sqlite:///energy_monitor.db
      - ML_MODEL_PATH=./ml_models
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: ecoshakti-network